### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by killerninja8** [UBC-MDS/datexplore#61]
I think we did pretty well! Here's the TA feedback (and penalty, in parentheses): 

**Function documentation**

- [ ] One or more documentations are missing one or more required elements (title, argument, returned, example) (-1)

- [ ] clean_names and detect_outliers function examples aren't complete — example of expected output (or description of that output) needs to be filled in (-1)

**Software package project structure**

- [x] datexplore.py file within src > datexplore directory is empty. you should delete this file if you aren't using it. (-3)

**Comment by jcairn02** [comment]
Looks good! Thanks for summarizing

**Comment by jcairn02** [comment]
All added
