### ISSUE TITLE
Milestone 4 Tasks

### ISSUE THREAD

**Issue by killerninja8** [UBC-MDS/datexplore#73]
- [ ] **Setup GitHub Action workflows to check your packages: build, test suite, code style (optional)**

These workflows should run on every push to any branch. For Python we recommend using the [ci-cd.yml file](https://github.com/py-pkgs/py-pkgs-cookiecutter/blob/main/%7B%7B%20cookiecutter.__package_slug%20%7D%7D/.github/workflows/ci-cd.yml) from the py-pkgs-cookiecutter repository.

- [ ] **Setup GitHub Action workflows**

So that the package is built and published to PyPI when pull requests are accepted to the main branch. The workflow should also use semantic versioning to automatically version the published releases. For Python we recommend using the [ci-cd.yml file](https://github.com/py-pkgs/py-pkgs-cookiecutter/blob/main/%7B%7B%20cookiecutter.__package_slug%20%7D%7D/.github/workflows/ci-cd.yml) from the py-pkgs-cookiecutter repository.

- [ ] **Choose a suitable license to your package and justify your choice (Issue created)**

- [ ] **Address feedback to improve the project (Issue created)**

> Source: https://pages.github.ubc.ca/MDS-2023-24/DSCI_524_collab-sw-dev_students/release/milestone4/milestone4.html
