### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by killerninja8** [UBC-MDS/datexplore#83]
I think we did fairly well! Here's some feedback from the TA:

- [ ] test.py should be deleted

- [ ] datexplore.py just combines clean_names.py, detect_outliers.py, and visualise.py files into one. either keep the last 3 listed and delete the first, or keep the first and delete the last 3.
- [ ]  (-1 * 2 function suites = -2; tests for detect_outliers and clean_names): For repeated variables that are shared across tests (e.g., unclean_df is created several times for clean_names tests), it would be more efficient to create a single object that contains your data that you can call to across tests, rather than repeatedly recreating it each time a different test is run.

> Additional suggestions: It might help you to look more into pytest decorators, including @pytest.fixture for case described above. You can read more about these here: https://py-pkgs.org/05-testing#advanced-testing-methods
